from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [
    cwd,
    cwd + '/../libraries/CMSIS/Device/ST/STM32H7xx/Include',
    cwd + '/../libraries/CMSIS/Include',
    cwd + '/../libraries/STM32H7xx_HAL_Driver/Inc',
    cwd + '/../libraries/CMSIS/RTOS',
]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
